# Generated by Django 6.1 on 2026-08-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='Название')),
                ('class_number', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], verbose_name='Класс')),
                ('department', models.CharField(choices=[('piano', 'Фортепиано'), ('guitar', 'Гитара'), ('vocal', 'Вокальное'), ('accordion', 'Баян'), ('balalaika', 'Домра')], max_length=40, verbose_name='Отделение')),
                ('file', models.FileField(upload_to='notes/', verbose_name='Файл нот')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='news_photos/', verbose_name='Фото')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='adminFunc.news', verbose_name='Новость')),
            ],
        ),
    ]
