# Generated by Django 6.1 on 2026-08-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='diplomas/', verbose_name='Файл грамоты')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='users.student', verbose_name='Ученик')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='Название экамена')),
                ('date', models.DateField(verbose_name='Дата экзамена')),
                ('mark', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_marks', to='users.teacher', verbose_name='Учитель')),
            ],
        ),
    ]
